import { User } from "@/types/user.types";

export const users: User[] = [
    {
      id: 'u1',
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      role: 'Admin',
      status: 'Active',
      createdAt: '2024-06-10T09:15:00Z',
    },
    {
      id: 'u2',
      name: 'Bob Smith',
      email: 'bob.smith@example.com',
      role: 'Editor',
      status: 'Inactive',
      createdAt: '2024-04-22T14:30:00Z',
    },
    {
      id: 'u3',
      name: 'Charlie Davis',
      email: 'charlie.davis@example.com',
      role: 'Viewer',
      status: 'Pending',
      createdAt: '2025-01-03T11:00:00Z',
    },
    {
      id: 'u4',
      name: 'Diana Martinez',
      email: 'diana.martinez@example.com',
      role: 'Editor',
      status: 'Active',
      createdAt: '2023-12-15T08:20:00Z',
    },
    {
      id: 'u5',
      name: 'Ethan Lee',
      email: 'ethan.lee@example.com',
      role: 'Admin',
      status: 'Active',
      createdAt: '2024-11-30T16:45:00Z',
    },
    {
      id: 'u6',
      name: 'Fiona Chen',
      email: 'fiona.chen@example.com',
      role: 'Viewer',
      status: 'Inactive',
      createdAt: '2023-09-05T12:10:00Z',
    },
    {
      id: 'u7',
      name: 'George White',
      email: 'george.white@example.com',
      role: 'Editor',
      status: 'Active',
      createdAt: '2024-02-18T07:35:00Z',
    },
    {
      id: 'u8',
      name: 'Hannah Patel',
      email: 'hannah.patel@example.com',
      role: 'Viewer',
      status: 'Pending',
      createdAt: '2025-03-25T10:50:00Z',
    },
    {
      id: 'u9',
      name: 'Isaac Kim',
      email: 'isaac.kim@example.com',
      role: 'Admin',
      status: 'Inactive',
      createdAt: '2023-08-11T15:00:00Z',
    },
    {
      id: 'u10',
      name: 'Jasmine Garcia',
      email: 'jasmine.garcia@example.com',
      role: 'Editor',
      status: 'Active',
      createdAt: '2024-05-20T13:25:00Z',
    },
  ];
  